### ISSUE TITLE
Filtering out Microsatellites for which Primers weren't generated

### ISSUE THREAD

**Issue by Alaneus** [lmdu/krait#1]
I'm using Krait to design primers for whole genomes. The genome sequences are present in scaffolds. Thus, if a microsatellite is present at the start or end of scaffold, the primer designing fails. I wish to filter out these failed microsatellites so as to combine microsatellite list and primer list. Deleting all the failed microsatellites manually is too much of a chore.

**Comment by lmdu** [comment]
I am sorry for the inconvenience. This version can not filter out microsatellites without primers. In the future version, we will add supporting for direct export microsatellites with designed primers.

**Comment by Alaneus** [comment]
Thank you.

**Comment by Dalini1299** [comment]
I am using KRAIT tool for mining microsatellites from the transcriptome data. Its working good, but when I try to design primers it is showing error. How to overcome with this issue. Please help me to sort out this problem.
