### ISSUE TITLE
Error with erroneous sequence data

### ISSUE THREAD

**Issue by Rhynchites** [lmdu/krait#11]
When searching for SSRs in a large fasta file (with more than 250 000 sequences) I get the following error:

![image](https://user-images.githubusercontent.com/69816216/90430517-dc752580-e0c7-11ea-9d6c-3f467132d3c9.png)

This is apparently triggered by erroneous sequence data, so far I traced back two sequences that did this, see attached files.

[NODE_12838_length_70_cov_23.79.txt](https://github.com/lmdu/krait/files/5086158/NODE_12838_length_70_cov_23.79.txt)
[NODE_42629_length_65_cov_2.692.txt](https://github.com/lmdu/krait/files/5086159/NODE_42629_length_65_cov_2.692.txt)

**Comment by mong222** [comment]
I also have the same error.
Could you tell me how to remove the erroneous data?

**Comment by Rhynchites** [comment]
Hi, Unfortunately I haven't found a way to remove the problematic sequence data in an efficient way yet.
It took me more than 2 hours to find those two sequences triggering the error.

It would be great if there was an option to ignore/skip those sequences, without having a crash of Krait.

**Comment by lmdu** [comment]
Thank you for reporting this bug. I will fix it as soon as possible!

**Comment by lmdu** [comment]
A new version was released to fix this bug. It was caused by sequence without G or C base, when counting the bases.

**Comment by mong222** [comment]
I tried the new version, but it crashed without errors when searching for SSRs in a large fasta file obtained from NCBI (more than 300 000 sequences).

**Comment by Rhynchites** [comment]
The new version of Krait ran my file without problems this time. Thanks for fixing this!
