### ISSUE TITLE
Multithreading support?

### ISSUE THREAD

**Issue by JerryCheng-96** [lmdu/krait#2]
The tool is wonderful and fast, but when I was using Krait to find the SSRs in the genome of Canis lupus famalaris, it seemed that it's running on a single thread. Is there any multithreading support?

**Comment by lmdu** [comment]
I am sorry, multithreading is not supported in current version.  But we are struggling to add support for using multiple CPUs to process more sequences at the same time in our next command line version of this tool. The command line version will be released soon, maybe next month.
