### ISSUE TITLE
Error: Need more than 1 value to unpack error

### ISSUE THREAD

**Issue by Yedomon** [lmdu/krait#4]
Dear Dr Du,
For SSRs location, I got this error message. I use a gff file. Please, how can I solve this issue?

![Screenshot from 2019-07-05 01-02-47](https://user-images.githubusercontent.com/45568831/60678873-cf47a800-9ec0-11e9-81ff-3b546f27e03f.png)

**Comment by lmdu** [comment]
I have optimized the GFF parser and a new version was released. The "locate function" was changed into "Mapping"

**Comment by Yedomon** [comment]
Thank you so much
