### ISSUE TITLE
Sudden die during statistical analysis

### ISSUE THREAD

**Issue by takeiga** [lmdu/krait#8]
Thanks for your effort in renewed version. However v1.1.0 could search microsatellite loci successfully but suddenly die during statistical analysis. I found that the several libraries are incompatible in my environment (Ubuntu 18.04) when I run from terminal and so replaced some libraries in Krait folder. But the program still die after indicating "Could not find QtWebEngineProcess". Thank you in advance for fixing this problem.

**Comment by takeiga** [comment]
Fixed by myself. This caused by folder name error (special character in Japanese).
Another error subsequently comes from Qt and nouveau compatibility, but I fixed that by installing nvidia driver. Finally I succeeded to get statistics! Thanks a lot!

**Comment by lmdu** [comment]
Nice work, thank you. We have removed the Qtwebengine from the newest version as it's too heavy and caused much errors for package. The lastest release allows you to directly export html statistical report. You can view results using Chrome or Firefox browsers.
